version: "3.8"
services:
  platform: linux/amd64
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      - PATH=./node_modules/.bin:$PATH
    ports:
      - "8501:8501"
